site_name: mscmivida
site_description: Supporting code for the mscMIVIDA project.
site_author: Duarte Folgado

# repo_url: INSERT_REPO_URL_HERE
# edit_uri_template: "browse/docs/{path}"

theme:
    name: 'material'
    locale: en
    font: false

plugins:
    - search
    - gen-files:
        scripts:
            - docs/generate_api_reference.py
    - literate-nav:
        nav_file: SUMMARY.md
    - section-index
    - mkdocstrings:
        handlers:
            python:
                paths: [src]

nav:
    - Home: index.md
    - API Reference: api_reference/

# WIP
#markdown_extensions:
#  - mkautodoc
#plugins:
#  - mkdocs-jupyter
